version: '3.8'

services:
  # Votre RabbitMQ mis à jour avec vos identifiants root/root
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # Port AMQP
      - "15672:15672" # Port interface web
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  # Ajout de la base de données PostgreSQL
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rabitmq_project_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  rabbitmq_data:
  postgres_data:
